// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Tabbed Interface</title><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"></head><body class=\"p-10 bg-gray-100\"><!-- Tab Buttons --><div class=\"flex\"><!-- Shared File Tab --><button onclick=\"showTab(&#39;sharedFileTab&#39;, &#39;sharedFileButton&#39;)\" id=\"sharedFileButton\" class=\"flex items-center px-4 py-2 space-x-2 font-semibold text-purple-600 bg-purple-100 rounded-l-lg tab-button\"><svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M13 7a3 3 0 11-2.24 5.01l-2.72 1.7a3 3 0 110-3.42l2.72 1.7A3 3 0 1113 7zm-9 6a3 3 0 105.99-.001A3 3 0 004 13zm11.28-9.03a3 3 0 10-1.02 5.82l-2.72 1.7a3 3 0 100 1.42l2.72-1.7a3 3 0 101.02-5.82z\"></path></svg> <span>Shared File</span>flex items-center px-4 py-2 space-x-2 font-semibold text-purple-600 bg-purple-100 rounded-l-lg tab-button</button><!-- Local File Tab --><button onclick=\"showTab(&#39;localFileTab&#39;, &#39;localFileButton&#39;)\" id=\"localFileButton\" class=\"flex items-center px-4 py-2 space-x-2 text-gray-600 bg-white rounded-r-lg tab-button\"><svg class=\"w-5 h-5\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M9 2a1 1 0 00-.707.293l-5 5a1 1 0 000 1.414l5 5a1 1 0 001.414-1.414L6.414 10H15a1 1 0 100-2H6.414l3.293-3.293A1 1 0 009 2z\"></path></svg> <span>Local File</span></button></div><!-- Tab Content --><div id=\"sharedFileTab\" class=\"mt-4 tab-content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Index().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"localFileTab\" class=\"hidden mt-4 tab-content\"><h2 class=\"mb-4 text-lg font-semibold text-gray-700\">Local Files</h2><p class=\"text-gray-600\">This is the content for the Local File tab.</p></div><script>\n    function showTab(tabId, buttonId) {\n      // Get all tab content and buttons\n      const tabs = document.querySelectorAll(\".tab-content\");\n      const buttons = document.querySelectorAll(\".tab-button\");\n\n      // Hide all tabs and reset button styles\n      tabs.forEach(tab => tab.classList.add(\"hidden\"));\n      buttons.forEach(button => {\n        button.classList.remove(\"bg-purple-100\", \"text-purple-600\", \"font-semibold\");\n        button.classList.add(\"bg-white\", \"text-gray-600\");\n      });\n\n      // Show the selected tab and apply active styles\n      document.getElementById(tabId).classList.remove(\"hidden\");\n      document.getElementById(buttonId).classList.add(\"bg-purple-100\", \"text-purple-600\", \"font-semibold\");\n    }\n\n    // Set default active tab on page load\n    document.addEventListener(\"DOMContentLoaded\", () => {\n      showTab('sharedFileTab', 'sharedFileButton');\n    });\n  </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
