// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index7() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>File Upload</title><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"></head><body class=\"flex items-center justify-center min-h-screen bg-gray-100\"><div class=\"text-center\"><form action=\"/upload\" method=\"post\" enctype=\"multipart/form-data\" class=\"space-y-4\"><!-- File Upload Button --><label for=\"file-upload\" class=\"px-4 py-2 text-white transition bg-blue-500 rounded-lg cursor-pointer hover:bg-blue-600\">Choose File</label><!-- Hidden File Input --><input id=\"file-upload\" type=\"file\" name=\"file\" class=\"hidden\" onchange=\"displayFileName(event)\"><!-- Display the selected file name --><p id=\"file-name\" class=\"text-gray-700\"></p><!-- Submit Button --><button type=\"submit\" class=\"px-4 py-2 text-white transition bg-green-500 rounded-lg hover:bg-green-600\">Upload File</button></form></div><script>\n    function displayFileName(event) {\n      const file = event.target.files[0];\n      const fileNameDisplay = document.getElementById(\"file-name\");\n      fileNameDisplay.textContent = file ? `Selected file: ${file.name}` : \"No file selected\";\n    }\n  </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
