// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>File Download</title><style>\n    /* Styles for disabled button */\n    #downloadButton:disabled {\n        background-color: gray;\n        cursor: not-allowed;\n    }\n    /* Styling for selected row */\n    .selected {\n        background-color: lightblue;\n    }\n</style></head><body><div class=\"file-table\"><table><thead><tr><th>NAME</th><th>SIZE</th><th>HASH INFORMATION</th><th>ONLINE SEEDER</th></tr></thead> <tbody><tr class=\"cursor-pointer\" onclick=\"selectRow(this)\"><td>Congdeptra1</td><td>95.7 MB</td><td>247.8 kB/s</td><td>5</td></tr><tr class=\"cursor-pointer\" onclick=\"selectRow(this)\"><td>Cotrai</td><td>95.7 MB</td><td>247.8 kB/s</td><td>4</td></tr></tbody></table></div><button id=\"downloadButton\" disabled>Download File</button><script>\n        function selectRow(row) {\n            // Deselect any previously selected row\n            let selectedRow = document.querySelector('.selected');\n            if (selectedRow) selectedRow.classList.remove('selected');\n\n            // Select the clicked row\n            row.classList.add('selected');\n\n            // Enable the download button\n            document.getElementById('downloadButton').disabled = false;\n        }\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
